### ISSUE TITLE
Reverse Initiative order messing up the ini rolls?

### ISSUE THREAD

**Issue by Raldanash** [fvtt-fria-ligan/blade-runner-foundry-vtt#20]
I had a little test with the system today and found that with Reverse Initiative Order installed, rolling ini from the combat tracker did not yield an ini value. The individual d20 icons next to each combatant were also missing. 

Disabling the module cleared the error. Just flagging it here as the System Instructions recommend Reverse Initiative as a module.

Foundry 10.291
BR 710.0.2

Console output - 
Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression ""
[No packages detected]
    at Roll.safeEval (foundry.js:9397:13)
    at Roll._evaluateTotal (foundry.js:9313:36)
    at Roll._evaluate (foundry.js:9261:24)
    at Roll.evaluate (foundry.js:9221:25)
    at Combat.rollInitiative (foundry.js:18591:18)
    at Combat.rollNPC (foundry.js:18654:17)
    at CombatTracker._onCombatControl (foundry.js:74816:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:74753:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by Stefouch** [comment]
I don't know why, but Reverse Initiative Order module now resets the `CONFIG.Combat.initiative` configuration.
But, adding also the formula in the system manifest ( `game.system.initiative` ) fixes the issue.

**Comment by Stefouch** [comment]
Reverse Initiative Order is no more needed with the release of the new **Year Zero Engine: Combat** module:

https://foundryvtt.com/packages/yze-combat
